name = "hono-drizzle-backend"
main = "src/index.ts"
compatibility_date = "2024-02-20"

[[d1_databases]]
binding = "DB"
database_name = "hono_drizzle_db"
database_id = "d36b5206-a4c4-4102-9f53-25b265dd17b2" 